## 创建张量

In [11]:
# 导入基础库
import paddle
import numpy as np

# 直接使用python列表的形式创建tensor
tensor_ndim_1 = paddle.to_tensor([1,2,3,4],dtype=paddle.float32)
print(tensor_ndim_1)

# 使用numpy对象直接转化成tensor对象
tensor_ndim_2 = paddle.to_tensor(data=np.ones((2,2)),dtype=paddle.float32)
print(tensor_ndim_2)

# 直接使用paddle自带的函数创建tensor对象
tensor_ndim_3 = paddle.ones((2,2,3),dtype=paddle.float32)
print(tensor_ndim_3)

Tensor(shape=[4], dtype=float32, place=Place(cpu), stop_gradient=True,
       [1., 2., 3., 4.])
Tensor(shape=[2, 2], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[1., 1.],
        [1., 1.]])
Tensor(shape=[2, 2, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


## tensor里面的属性

In [7]:
print(tensor_ndim_3.ndim) # 维度信息
print(tensor_ndim_3.shape) # shape信息
print(tensor_ndim_3.size) # 元素个数
print(tensor_ndim_3.numpy()) # 还原成np格式

3
[2, 2, 3]
12
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## tensor进行计算

In [8]:
sum_a = paddle.to_tensor([[1,2,3],[4,5,6]],dtype=paddle.float32)
sum_b = paddle.to_tensor([[5,6,7],[8,9,10]],dtype=paddle.float32)
sum_a + sum_b

Tensor(shape=[2, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[6. , 8. , 10.],
        [12., 14., 16.]])

## 关于axis的使用

In [9]:
from matplotlib.pyplot import axis


a = paddle.ones((2,5,4),dtype=paddle.float32)
# 这里我们需要按照 axis = [1,2] 求和 其实就是吧 上面的shape里面的 1 , 2 对应索引位置的值消除 所以最后就是2
paddle.sum(a,axis=[1,2])

Tensor(shape=[2], dtype=float32, place=Place(cpu), stop_gradient=True,
       [20., 20.])

In [5]:
# 这里还有一个参数叫keepdim如果设置为True，那么对应原本需要消除的数据们现在直接给1
paddle.sum(a,axis=[1],keepdim=True)

Tensor(shape=[2, 1, 4], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[5., 5., 5., 5.]],

        [[5., 5., 5., 5.]]])